In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 101, size=(5, 5))
print('Array:',array)

Array: [[34 17 72 26 46]
 [86 28 38 23 69]
 [93 58 90 69 20]
 [54  2 22 88 18]
 [18 57 27 19 94]]


In [3]:
mid = array[2, 2]
print("Middle Element:", mid)

Middle Element: 90


In [4]:
means = array.mean(axis=1)
print("\nMean of Each Row:", means)


Mean of Each Row: [39.  48.8 66.  36.8 43. ]


In [5]:
mean = array.mean()
greater_than_mean = array[array > mean]
print("Elements Greater than Overall Mean are:", greater_than_mean)

Elements Greater than Overall Mean are: [72 86 69 93 58 90 69 54 88 57 94]


In [6]:
def numpy_spiral_order(matrix):
    spiral_order = []
    while matrix.size:
        spiral_order.extend(matrix[0])
        matrix = matrix[1:].T[::-1]
    return spiral_order

spiral_order_elements = numpy_spiral_order(array)
print("\nSpiral Order Elements:", spiral_order_elements)


Spiral Order Elements: [34, 17, 72, 26, 46, 69, 20, 18, 94, 19, 27, 57, 18, 54, 93, 86, 28, 38, 23, 69, 88, 22, 2, 58, 90]
